use_frameworks!

platform :ios, '10.0'

target 'SwiftHelpers_Tests' do
  pod 'SwiftHelpers', :path => '../'
  
  pod 'Quick', '~> 1.3.4'
  pod 'Nimble', '~> 7.3.1'
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
#      config.build_settings['SWIFT_VERSION'] = '4.2'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
